blueprint:
  name: Growatt Charger Control
  description: Control a Growatt charger with flexibility.
  domain: automation

input:
  solax_integration_name:
    name: Solax Integration Name
    description: Name of the Solax integration (e.g., "growatts")

trigger:
  platform: state
  entity_id: input_boolean.start_growatt_charge
  to: "on"

action:
  - service: select.select_option
    data_template:
      entity_id: !input solax_integration_name
      option: >-
        {{ states('input_datetime.growatt_start_time') |
        regex_replace(':[0-9]{2}$', '') }}
    enabled: true
  - service: select.select_option
    data_template:
      entity_id: !input solax_integration_name
      option: >-
        {{ states('input_datetime.growatt_end_time') |
        regex_replace(':[0-9]{2}$', '') }}
    enabled: true
  - service: select.select_option
    data_template:
      entity_id: !input solax_integration_name
      option: 'Ændr growatts Charger Time 1-mulighed'
    enabled: true
  - service: select.select_option
    data_template:
      entity_id: !input solax_integration_name
      option: 'Ændr growatts Charger Switch-mulighed'
    enabled: true
  - service: input_boolean.turn_off
    entity_id: input_boolean.start_growatt_charge

mode: single
