blueprint:
  name: Growatt Charger Control
  description: Control a Growatt charger.

  input:
    solax_integration_name:
      name: Solax Integration Name
      description: Name of the Solax integration (e.g., "growatts")
      selector:
        entity:
          domain: solax_integration

  trigger:
    platform: state
    entity_id: input_boolean.start_growatt_charge
    to: "on"

  action: []

mode: single
